name: ice_code_editor
version: 0.0.9
description: Code Editor + Preview
authors:
- Chris Strom <chris@eeecomputes.com>
- Santiago Arias <santiago.ariassar@gmail.com>
- Srdjan Pejic <spejic@gmail.com>
homepage: https://github.com/eee-c/ice-code-editor
dependencies:
  unittest: ">=0.6.5 <0.6.6"
  js: ">=0.0.24 <0.0.25"
  crypto: ">=0.6.5 <0.6.6"
  ctrl_alt_foo: any
