name: ice_code_editor
version: 0.2.1
description: Code Editor + Preview
authors:
- Chris Strom <chris@eeecomputes.com>
- Santiago Arias <santiago.ariassar@gmail.com>
- James Hurford <terrasea@gmail.com>
- Srdjan Pejic <spejic@gmail.com>
homepage: https://github.com/eee-c/ice-code-editor
dependencies:
  browser: ">=0.9.0 < 0.10.0"
  crypto: ">=0.9.0 < 0.10.0"
  ctrl_alt_foo: ">=0.3.0 <0.3.1"
  polymer: any
dev_dependencies:
  unittest: any
transformers:
  - $dart2js:
      minify: true
